name: "SBOM"
on: workflow_dispatch

jobs:
  sbom_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: analyze sbom
        uses: anchore/sbom-action@v0
        with:
          path: .
      - name: publish sbom
        uses: anchore/sbom-action/publish-sbom@v0
        with:
          sbom-artifact-match: ".*\\.spdx$"
